spring.application.name=gift-quiz-server
spring.datasource.url=${SPRING_DATASOURCE_URL:${DATABASE_URL:jdbc:h2:file:./gift-quiz-server/data/gift-quiz-db}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DATABASE_USERNAME:sa}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DATABASE_PASSWORD:}}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=${H2_CONSOLE_ENABLED:false}
server.port=${PORT:8080}
